"""Initial migration

Revision ID: 8ca71972b866
Revises: 
Create Date: 2024-04-06 00:33:36.622759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca71972b866'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_quota', sa.Integer(), nullable=False),
    sa.Column('remaining_quota', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_record',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('identifier_key', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_survey_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_quota', sa.Integer(), nullable=False),
    sa.Column('remaining_quota', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('survey_rec_id', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotation_sentences',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('outlet', sa.String(length=100), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['survey_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_consent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('survey_record_id', sa.String(length=150), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['survey_record_id'], ['survey_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demographics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('survey_record_id', sa.String(length=150), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('education', sa.Integer(), nullable=False),
    sa.Column('native_english_speaker', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['survey_record_id'], ['survey_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ideologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('survey_record_id', sa.String(length=150), nullable=True),
    sa.Column('political_ideology', sa.Integer(), nullable=True),
    sa.Column('followed_news_outlets', sa.Text(), nullable=True),
    sa.Column('news_check_frequency', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_record_id'], ['survey_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('survey_record_id', sa.String(length=150), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['survey_record_id'], ['survey_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_annotation_sentences',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('outlet', sa.String(length=100), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['test_survey_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('range_slider_choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_range', sa.Integer(), nullable=False),
    sa.Column('max_range', sa.Integer(), nullable=False),
    sa.Column('label_left_side', sa.String(length=100), nullable=False),
    sa.Column('label_right_side', sa.String(length=100), nullable=False),
    sa.Column('selected', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simple_choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=False),
    sa.Column('selected', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_annotations',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('survey_record_id', sa.String(length=150), nullable=True),
    sa.Column('annotation_sentence_id', sa.String(length=150), nullable=True),
    sa.Column('sentence_group_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.Integer(), nullable=False),
    sa.Column('words', sa.Text(), nullable=False),
    sa.Column('factual', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_sentence_id'], ['annotation_sentences.id'], ),
    sa.ForeignKeyConstraint(['sentence_group_id'], ['survey_groups.id'], ),
    sa.ForeignKeyConstraint(['survey_record_id'], ['survey_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_survey_annotations',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('survey_record_id', sa.String(length=150), nullable=True),
    sa.Column('annotation_sentence_id', sa.String(length=150), nullable=True),
    sa.Column('sentence_group_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.Integer(), nullable=False),
    sa.Column('words', sa.Text(), nullable=False),
    sa.Column('factual', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_sentence_id'], ['test_annotation_sentences.id'], ),
    sa.ForeignKeyConstraint(['sentence_group_id'], ['test_survey_groups.id'], ),
    sa.ForeignKeyConstraint(['survey_record_id'], ['survey_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_survey_annotations')
    op.drop_table('survey_annotations')
    op.drop_table('simple_choices')
    op.drop_table('range_slider_choices')
    op.drop_table('test_annotation_sentences')
    op.drop_table('questions')
    op.drop_table('quality_control')
    op.drop_table('ideologies')
    op.drop_table('demographics')
    op.drop_table('data_consent')
    op.drop_table('annotation_sentences')
    op.drop_table('user_pool')
    op.drop_table('test_survey_groups')
    op.drop_table('surveys')
    op.drop_table('survey_record')
    op.drop_table('survey_groups')
    # ### end Alembic commands ###
